version: "3"
services:
  frontend:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=development
    command: npm start


